version: "3.9"
services:
  mysql:
    build:
      context: ./
      dockerfile: ./Dockerfile
    image: jp3pe/spring-boot-bulletin-board/mysql
    container_name: mysql
    command:
      # 한글과 이모지 입력을 위하여 기본 문자셋 인코딩 변경
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    ports:
      - "3306:3306"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example